docRoot                   /var/www/vhosts/demo

context / {
  type                    proxy
  handler                 app
  addDefaultCharset       off
}

module cache {
  ls_enabled              1
  checkPublicCache        1
  enableCache             0
}
